FROM ruby

ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user

RUN curl -fsSL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g yarn

ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH


RUN mkdir /usr/src/cache
RUN gem install rails bundler

WORKDIR /usr/src/cache

COPY package.json .
COPY yarn.lock .
COPY Gemfile .
COPY Gemfile.lock .
RUN bundle install --path vendor
RUN yarn install

WORKDIR $INSTALL_PATH
RUN chown -R user:user /opt/app
RUN chown -R user:user /usr/src/cache

RUN apt-get install rsync  -y

USER $USER_ID
CMD bash -c "rsync -a /usr/src/cache/node_modules $INSTALL_PATH && rsync -a /usr/src/cache/vendor $INSTALL_PATH && bundle exec rails"
