version: "3"
services:
  db:
    image: postgres
    networks:
      - production
    environment:
      - POSTGRES_USER=production
      - POSTGRES_DATABASE=production
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - $PWD/postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
      - $PWD/postgres-config/pg_hba.conf:/conf/pg_hba.conf
      - $PWD/pgconf:/pgconf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5432:5432"
  nginx:
    networks:
      - production
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    environment:
      - PRIVATE_KEY_PASS=${PRIVATE_KEY_PASS}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/nginx/reverse-proxy.conf:/etc/nginx/nginx.conf
  redis:
    networks:
      - production
    image: redis
    ports:
      - "6379:6379"
networks:
    production:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.211.0/24
