development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6380/1" } %>
  channel_prefix: cmqueue_development

test:
  adapter: test
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6382/1" } %>
  channel_prefix: cmqueue_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>
  channel_prefix: cmqueue_production
