refresh_active_staff:
  cron: "*/5 * * * *"
  class: "RefreshActiveStaffJob"
  queue: default
  retries: 0
backup_database:
  cron: "0 0 * * *"
  class: "System::BackupDatabaseJob"
  queue: default
  retries: 0
migrate_enrollments:
  cron: "0 0 18 1,5,8,12 *"
  class: "Courses::MigrateAndArchivePastEnrollmentsJob"
  queue: default
  retries: 0
ping_users:
  cron: "*/3 * * * *"
  class: "PingJob"
  queue: default
  retries: 0