on:
  push:
    branches:
      - production
jobs:
  deploy_server:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ github.event.repository.name }}
          git checkout production
          git pull --rebase origin production
          RAILS_ENV=production rails db:migrate
          RAILS_ENV=production rails restart
  deploy_heroku:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: cmqueue-demo
        heroku_email: arthurdzieniszewski@gmail.com
        branch: "production"

